# Site settings
title: Sheryl Hsiung
description: From Taiwan now lives in Pittsburgh.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Sheryl Hsiung

# Collection settings
collections:
  photos:

# Social settings
github_url: https://github.com/jjuhsiung
linkedin_url: https://www.linkedin.com/in/jihanhsiung/

# Build settings
markdown: kramdown
